export const ACTIVITY_ENTITY_TYPES = [
	'customer',
	'subscription',
	'wallet',
	'wallet_transaction',
	'entitlement_grant',
	'invoice',
	'invoice_line_item',
	'subscription_line_item',
	'payment',
	'payment_method',
	'refund',
	'credit_note',
	'checkout_session',
	'subscription_phase',
	'subscription_schedule',
	'subscription_pause',
	'credit_grant',
	'credit_grant_application',
	'coupon_association',
	'coupon_application',
	'addon_association',
	'tax_association',
	'plan',
	'price',
] as const;

export const ACTIVITY_ACTIONS = [
	'customer.created',
	'customer.updated',
	'customer.deleted',
	'subscription.created',
	'subscription.updated',
	'subscription.paused',
	'subscription.resumed',
	'subscription.cancelled',
	'subscription.plan_changed',
	'invoice.created',
	'invoice.updated',
	'invoice.finalized',
	'invoice.voided',
	'invoice.paid',
	'wallet.created',
	'wallet.updated',
	'wallet_transaction.created',
	'entitlement_grant.created',
	'plan.created',
	'plan.updated',
	'plan.prices_synced',
	'price.created',
	'price.updated',
	'price.archived',
	'payment.created',
	'payment.updated',
] as const;

export const ACTIVITY_ACTOR_TYPES = ['user', 'api_key', 'system', 'customer_portal'] as const;
